### ISSUE TITLE
max_line_length should support non ASCII characters

### ISSUE THREAD

**Issue by MyIgel** [editorconfig-checker/editorconfig-checker#115]
Currently it seems like `ä`, `ö` and `ü` are counted as two characters which makes the `max_line_length` rule not usable for not plain ASCII files (like UTF-8 so everything with emojis which maybe should also count as one character ;))

**Comment by mstruebing** [comment]
Starting point: make the line variable more flexible here: https://github.com/editorconfig-checker/editorconfig-checker/blob/master/pkg/validation/validators/validators.go#L144
