### ISSUE TITLE
Version difference in javascript package?

### ISSUE THREAD

**Issue by lorengordon** [editorconfig-checker/editorconfig-checker#138]
Not really an issue, just curious on why the [javascript package is version 3.3.0](https://www.npmjs.com/package/editorconfig-checker), when it seems that current release is 2.2.0?

**Comment by mstruebing** [comment]
You mean the difference between the "core"-golang package and the javascript wrapper?

At the beginning, there was no core, there was only a PHP version, later I created a JavaScript version.
I realizied, I'm implementing the same features, and if I add new I will do it two times. This is annoying and I thought I only want to implement it one time. So I found Go and created a core version, a Javascript version was already released, so I couldn't start at 1.0.0 and needed to increase the version number as a major version as it was a breaking change.

Does that answer your question?

**Comment by lorengordon** [comment]
Guess I'm not too sure about the terminology of "core" vs "wrapper"... I don't see that mentioned in the readme or ghpages? But I think you're saying this project started in one programming language, PHP, released versions, and later wrote the same tool in a different language, Javascript, and started over with a new version, and then switched again to Go and performed some voodoo magic to release to all programming languages and package repos  (e.g. python), starting over again with a new versioning scheme. So now there are all these different version identifiers depending on the user's install mechanism.

I guess it doesn't really matter, was just a bit confusing when I first installed the javascript version and got 3.3.0, and then someone else on my team installed the python version and got 2.1.0, and then we checked GitHub Releases and saw 2.2.0. And now I'm seeing the PHP version is 10.2.0!

Honestly, hats off to you, I've never seen anyone release the same tool in multiple different programming languages and packages, at the same time. Slick work.

I suppose if it were of any interest, you could align them all under a single new version, say 11.0.0, and not worry about individual versions.

**Comment by mstruebing** [comment]
Yep, you are right with your assumption. Thank you :tada: 
I have future plans to make the "core"(go) version independent form the "wrapper" (javascript/python/...) - I want to be able to define the core version in the configuration file. But I'm a bit busy right now.
You can see a WIP pull request here: https://github.com/editorconfig-checker/editorconfig-checker.javascript/pull/222

**Comment by lorengordon** [comment]
I'll go ahead and close this, since now it is evident the versions are being set and tagged in each wrapper's individual repository (e.g. https://github.com/editorconfig-checker/editorconfig-checker.python). I didn't even check the GitHub org before, so didn't see all the other repositories.
