### ISSUE TITLE
.ecrc disable is unclear

### ISSUE THREAD

**Issue by stepancheg** [editorconfig-checker/editorconfig-checker#143]
Consider this config:

```
{
  "Disable": {
    "Indentation": false,
    "IndentSize": false,
  }
}
```

To disable the indentation checks, should the config option should be `true` or `false`? It's unclear from the readme. Can you please update the readme?

**Comment by mstruebing** [comment]
Thank you for that issue @stepancheg 
If you want, you can create a Pull Request to make the docs more clear, that would be great :tada:

**Comment by stepancheg** [comment]
For now I'm struggling editorconfig-checker to use these options. No combination seems to work.

**Comment by stepancheg** [comment]
OK, it is `true` to disable.
