### ISSUE TITLE
Gradle plugin available?

### ISSUE THREAD

**Issue by takanuva15** [editorconfig-checker/editorconfig-checker#153]
Hi, thanks for making this awesome lint checker. Looking forward to additional features as you add them. 

I wanted to know whether there was a gradle plugin available for this so that I could easily import this and run editorconfig checks on my gradle projects?

**Comment by mstruebing** [comment]
Hey @takanuva15 thank you for your very kind words.

Unfortunately, there is no such thing currently.
I'm not really sure about Gradle, but it is a Java build tool, right? So do the tools/plugins executed there needs to be Java tools or can it be any binary?

Anyway, feel free to create some plugin yourself if you feel comfortable, and if you want we can also add this to the organization.

**Comment by takanuva15** [comment]
Ah ok I see, thanks!
