### ISSUE TITLE
Rate limiting: causing TypeError: json.map is not a function

### ISSUE THREAD

**Issue by omusavi** [editorconfig-checker/editorconfig-checker#156]
This error started popping up in our mega-linter runs in our CI system as well as locally, but very intermittently. Was a strange one but I think I tracked it down to the [latest commit](https://github.com/editorconfig-checker/editorconfig-checker.javascript/commit/b9f6f2cfd918a0dbcfd9c36f5e7819e7b8456758). 

Basically, the call to `getAvailableVersions` pings github, but if we do that too much, github rate limits us:

```
{"message":"API rate limit exceeded for <my ip address redacted> (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

This causes an error in the json.map call inside `getAvailableVersions`

```
ERROR: TypeError: json.map is not a function
    at /node_modules/editorconfig-checker/dist/lib.js:160:22
    at step (/node_modules/editorconfig-checker/dist/lib.js:52:23)
    at Object.next (/node_modules/editorconfig-checker/dist/lib.js:33:53)
    at fulfilled (/node_modules/editorconfig-checker/dist/lib.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Unfortunately, using `--skip-update-check` also does not work because `--skip-update-check` is checked **after** the call to `getAvailableVersions`.

This issue popped up for us using the mega-linter, and as I understand it, mega-linter will call editorconfig-checker for every file that needs to be checked....which can be a lot and quickly will cause a rate limiting issue.

**Comment by mstruebing** [comment]
Thank you very much. I wasn't aware of that issue and it was my mistake.
I rolled back the changes and released a new version.
