### ISSUE TITLE
Document exclude regex is on relative path

### ISSUE THREAD

**Issue by polarathene** [editorconfig-checker/editorconfig-checker#167]
I was using the `-dry-run` option which outputs absolute paths, and wondering why my config exclude was having trouble filtering out a top level directory...

Turned out that it's not applying regex based on the absolute path the dry run outputs, but [relative paths from where the command is run](https://github.com/editorconfig-checker/editorconfig-checker/pull/24)? That should be documented imo :sweat_smile:

**Comment by mstruebing** [comment]
Thank you very much for that issue.
Feel free to provide a pull request regarding that documentation changes, that would be great 👍
