### ISSUE TITLE
How to avoid undesirable `Wrong line endings or new final newline` error

### ISSUE THREAD

**Issue by hepcat72** [editorconfig-checker/editorconfig-checker#176]
I have a Django template for download of a tab-delimited file (a .tsv file).  I get the `Wrong line endings or new final newline` error unless my template ends with `\n\n`, which seems like an inappropriate requirement.  I simply added the extra newline to appease this requirement, but then I decided to split up the template into a parent template (which handles the header) and 2 child templates (1 of which is used each time and which are also subject to the same `\n\n` requirement).  The resulting downloaded file ends up with 3 newlines (`\n\n\n`) at the end.

For example, here are 2 of my templates (parent & 1 selected child sub-template).

#### Parent (`download.tsv`)
```
# Download Time: {{ dt }}
# Advanced Search Query: {% autoescape off %}{{ qry }}{% endautoescape %}
#{% if qry.selectedtemplate == "pgtemplate" %}
{% include "DataRepo/search/downloads/peakgroups.tsv" %}{% elif qry.selectedtemplate == "pdtemplate" %}{% include "DataRepo/search/downloads/peakdata.tsv" %}{% endif %}

```
#### Child (`peakdata.tsv`):
```
#Sample	Tissue	Animal	Infusate	Compound	Atom:Label	Corrected Abundance	Fraction
{% for pd in res.all %}{{ pd.peak_group.msrun.sample.name }}	{{ pd.peak_group.msrun.sample.tissue.name }}	{{ pd.peak_group.msrun.sample.animal.name }}	{{ pd.peak_group.msrun.sample.animal.tracer_compound.name }}	{{ pd.peak_group.name }}	{{ pd.labeled_element }}:{{ pd.labeled_count }}	{{ pd.corrected_abundance }}	{{ pd.fraction }}
{% endfor %}

```
If I remove the last extra newline from either file, I end up with the `Wrong line endings or new final newline` error.

Am I doing something wrong, because it doesn't seem like this scenario should require `\n\n` at the end of either file, let alone both?  Or is there something I can do that would avoid this error with just `\n` at the end of the last line?

For example, if the parent template is:

```
# Download Time: {{ dt }}
# Advanced Search Query: {% autoescape off %}{{ qry }}{% endautoescape %}
#{% if qry.selectedtemplate == "pgtemplate" %}
{% include "DataRepo/search/downloads/peakgroups.tsv" %}{% elif qry.selectedtemplate == "pdtemplate" %}{% include "DataRepo/search/downloads/peakdata.tsv" %}{% endif %}
```

I get this from superlinter:
```
2021-07-27 15:27:39 [INFO]   File:[/tmp/lint/DataRepo/templates/DataRepo/search/downloads/download.tsv]
2021-07-27 15:27:39 [ERROR]   Found errors in [editorconfig-checker] linter!
2021-07-27 15:27:39 [ERROR]   Error code: 1. Command output:
------
DataRepo/templates/DataRepo/search/downloads/download.tsv:
	Wrong line endings or new final newline

1 errors found
------
```

**Comment by hepcat72** [comment]
I think that the problem is somehow associated with the `VS Code` editor.  The editor was displaying 2 empty lines at the end of each file.  In fact, it was showing 1 empty line at the end of the files when I was getting the linting error - but I think it was lying to me.  I closed out VS Code and re-opened it, and now, even though it had 2 empty (numbered) lines at the end of each of the 3 files before (in fact, I even manually highlighted and copied the file and pasted it above with the 2 consecutive newlines), it now shows 1 empty (numbered) line at the end of each file.

So I'm closing this issue and am going to inspect my VS Code settings for something that might explain this weird editor behavior.

**Comment by D3vil0p3r** [comment]
@hepcat72 I have the same issue by using VSCodium. Did you get a solution?

**Comment by hepcat72** [comment]
I don't know what was causing it, but I suspect that something was maybe adding carriage return characters or something? I think you just have to manually futz with the line endings.
