### ISSUE TITLE
How to re-include excluded files

### ISSUE THREAD

**Issue by chalkygames123** [editorconfig-checker/editorconfig-checker#177]
Hi, thank you for creating such a great tool!

Is there any way to re-include files while not ignoring default excludes? Since I often manipulate SVG files by hand, I want to check them as well.

**Comment by mstruebing** [comment]
You can run the tool with the argument `ignore-defaults`:

```
➜ svg-test (master) ✗
$ echo 123 >> abc.svg
➜ svg-test (master) ✗
$ ../bin/ec -verbose
Exclude Regexp: \.yarn/|yarn\.lock$|package-lock\.json$|composer\.lock$|\.pnp\.cjs$|\.pnp\.js$|\.snap$|\.otf$|\.woff$|\.woff2$|\.eot$|\.ttf$|\.gif$|\.png$|\.jpg$|\.jpeg$|\.webp$|\.avif$|\.mp4$|\.wmv$|\.svg$|\.ico$|\.bak$|\.bin$|\.pdf$|\.zip$|\.gz$|\.tar$|\.7z$|\.bz2$|\.log$|\.patch$|\.css\.map$|\.js\.map$|min\.css$|min\.js$
Don't add abc.svg to be checked
0 files checked
➜ svg-test (master) ✗
$ ../bin/ec -verbose --ignore-defaults
Exclude Regexp:
Add abc.svg to be checked
Validate abc.svg
1 files checked
```

But keep in mind that all default excludes will be deactivated and you need to provide your own.

**Comment by chalkygames123** [comment]
Thanks for the quick response!

Is it impossible to re-include only specific files while keeping the default excludes? Something like this: `$ ec --include '\.svg$'`

**Comment by mstruebing** [comment]
No, that is not possible at this point. But you can take the default ones and add to your specific ones.

**Comment by chalkygames123** [comment]
Got it, I'll get it that way. Thank you!
