### ISSUE TITLE
TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by vanyauhalin** [editorconfig-checker/editorconfig-checker#178]
I don't understand how to solve this problem. Is there a problem with my system?

```
$ npm run editorconfig

> editorconfig
> ec

ERROR: Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/unpack.js:200:18)
    at Unpack.<anonymous> (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/parse.js:81:14)
    at Unpack.emit (node:events:406:35)
    at Unpack.[emit] (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/parse.js:285:12)
    at Unpack.[maybeEnd] (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/parse.js:401:17)
    at Unpack.[consumeChunk] (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/parse.js:432:21)
    at Unpack.write (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/parse.js:364:25)
    at Unpack.end (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/tar/lib/parse.js:477:14)
    at Yallist.<anonymous> (/Users/vanyauhalin/Documents/programming-projects/test/node_modules/minipass/index.js:396:18) {
  recoverable: false,
  file: '/Users/vanyauhalin/Documents/programming-projects/test/node_modules/editorconfig-checker/dist/../ec.tar.gz',
  cwd: '/Users/vanyauhalin/Documents/programming-projects/test/node_modules/editorconfig-checker',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
```

<hr>

```
system macOS Big Sur 11.4 (M1)
npm 7.20.6
node v16.6.2
```

<details>
  <summary>
    <code>
      .ecrc
    </code>
  </summary>

```json
{
  "exclude": ["node_modules"]
}
```

</details>

<details>
  <summary>
    <code>
      .editorconfig
    </code>
  </summary>

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

</details>

<details>
  <summary>
    <code>
      .package.json
    </code>
  </summary>

```json
{
  "private": true,
  "scripts": {
    "editorconfig": "ec"
  },
  "devDependencies": {
    "editorconfig-checker": "^4.0.2"
  }
}
```

</details>

**Comment by mstruebing** [comment]
I think it it because we have not build an m1 version yet - but I'm not sure.
I have no m1 and can not reproduce the error therefore.

We need to create a release: https://dev.to/tidalmigrations/how-to-cross-compile-go-app-for-apple-silicon-m1-27l6

**Comment by mstruebing** [comment]
https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/316

**Comment by NetOperatorWibby** [comment]
Oh dang, I was hoping something else was the issue. Unfortunately, I don't know Go.

**Comment by pepelsbey** [comment]
Just got the same error on my M1 Max MacBook. Is there anything we can do to help you to release for M1?

**Comment by mstruebing** [comment]
@pepelsbey As releasing is still a manual step in this repository, I think a PR that would make sure to have the correct compile os/arch in the makefile: https://github.com/editorconfig-checker/editorconfig-checker/blob/master/Makefile#L114

I'm not sure it will work on my machine, so what would be even better would be to provide an automatic release step which handles all of it as a GitHub action https://github.com/editorconfig-checker/editorconfig-checker/issues/150

**Comment by mstruebing** [comment]
@pepelsbey @NetOpWibby could someone try if it works now?
I added a `darwin-arm64`-binary.

**Comment by NetOpWibby** [comment]
There isn't a new release on npm or here.

**Comment by mstruebing** [comment]
> https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/2.4.0

I added a binary for `darwin-arm64` to the latest releases, see here: ec-darwin-arm64.tar.gz

**Comment by vanyauhalin** [comment]
> > https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/2.4.0
> 
> I added a binary for `darwin-arm64` to the latest releases, see here: https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/2.4.0
> 
> If you run the javascript version and everything works as expected, it should use this binary.

Alas, but it doesn't work. First I created a new empty project and installed the package from npm. Afthe run `npm run lint` command and got the same error. Secondly, I downloaded `ec-darwin-arm64.tar.gz` from the GitHub repo and manually replaced the archive in the `node_modules` and... got the same error.

<details>
  <summary>Project details.</summary>

```sh
$ cat package.json 
{
  "name": "test-editor",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "ec"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "editorconfig-checker": "^4.0.2"
  }
}

$ ls -la 
total 40
drwxr-xr-x   7 vanyauhalin  staff    224 Feb  9 18:17 .
drwxr-xr-x@ 10 vanyauhalin  staff    320 Feb  9 18:14 ..
-rw-r--r--   1 vanyauhalin  staff    148 Feb  9 18:16 .editorconfig
drwxr-xr-x  20 vanyauhalin  staff    640 Feb  9 18:15 node_modules
-rw-r--r--   1 vanyauhalin  staff  11455 Feb  9 18:15 package-lock.json
-rw-r--r--   1 vanyauhalin  staff    231 Feb  9 18:17 package.json
drwxr-xr-x   3 vanyauhalin  staff     96 Feb  9 18:16 src

$ cd src && ls -la 
total 8
drwxr-xr-x  3 vanyauhalin  staff   96 Feb  9 18:16 .
drwxr-xr-x  7 vanyauhalin  staff  224 Feb  9 18:17 ..
-rw-r--r--  1 vanyauhalin  staff   30 Feb  9 18:16 index.js
```

</details>

**Comment by cfbao** [comment]
I'm starting to see this error on Linux and Windows today.

running in an empty folder:
```
C:\Code\testec> npx editorconfig-checker
ERROR: Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\warn-mixin.js:19:40)
    at Unpack.warn (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\unpack.js:220:18)
    at Unpack.<anonymous> (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\parse.js:81:14)
    at Unpack.emit (node:events:402:35)
    at Unpack.[emit] (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\parse.js:285:12)
    at Unpack.[maybeEnd] (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\parse.js:401:17)
    at Unpack.[consumeChunk] (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\parse.js:432:21)
    at Unpack.write (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\parse.js:364:25)
    at Unpack.end (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\tar\lib\parse.js:477:14)
    at Yallist.<anonymous> (C:\Users\cbao\AppData\Local\npm-cache\_npx\a1ec1b736e7e2ae1\node_modules\minipass\index.js:409:18) {
  recoverable: false,
  file: 'C:\\Users\\cbao\\AppData\\Local\\npm-cache\\_npx\\a1ec1b736e7e2ae1\\node_modules\\editorconfig-checker\\dist/../ec.tar.gz',
  cwd: 'C:/Users/cbao/AppData/Local/npm-cache/_npx/a1ec1b736e7e2ae1/node_modules/editorconfig-checker',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
```

**Comment by towry** [comment]
My solution is change node(v16) to node(v14)

**Comment by NetOpWibby** [comment]
Oh gross, we shouldn't have to regress to use this.

**Comment by Antoniossss** [comment]
Downgrading to node 14 here as well hoping it will fix the issue.

**Comment by mstruebing** [comment]
Anyone wants to try and find the root cause of that issue?

**Comment by sonjaerock** [comment]
asddf

**Comment by sonjaerock** [comment]
https://github.com/npm/cli/issues/3229#issuecomment-1141614715

**Comment by mstruebing** [comment]
Wow - great :D I wasn't really aware of that.

**Comment by chalkygames123** [comment]
Somehow this issue is recurring. I have totally no idea what the cause is 🤷

**Comment by chalkygames123** [comment]
@mstruebing Anything I can help you with on this?

**Comment by mihanizm56** [comment]
@chalkygames123 my current version is "editorconfig-checker": "4.0.2" - do i need to downgrade it to 2.5.0 ?

**Comment by mihanizm56** [comment]
this issue is still reproducible and should be reopened
during package install - I get the version with darwin/amd but not darwin/arm
![photo_2022-09-15_17-04-15](https://user-images.githubusercontent.com/37120827/190415161-b134013e-d864-4855-97c7-b4b36c899035.jpg)

**Comment by chalkygames123** [comment]
@mihanizm56 I'm not a maintainer, and you are confusing the core with its JavaScript wrapper 😅

**Comment by mihanizm56** [comment]
> @mihanizm56 I'm not a maintainer, and you are confusing the core with its JavaScript wrapper 😅

I know that this is the "core chat" - but issue is the same. during install i have wrong binary file

**Comment by chalkygames123** [comment]
I meant that version 2.5.0 does not exist in the JavaScript wrapper.

**Comment by willtho89** [comment]
I also encountered the problem. Turns out for the 4.0.2 and 4.0.1 releases the `CORE_VERSION` is hardcoded to 2.3.5, in the current master this is not the case.

So either set your package.json to 
`"editorconfig-checker": "editorconfig-checker/editorconfig-checker.javascript.git#master"`
and compile yourself, or just use `4.0.0` for now.

@mstruebing any news on an update here?
