### ISSUE TITLE
feat: editorconfig-checker-disable-next-line

### ISSUE THREAD

**Issue by andreineculau** [editorconfig-checker/editorconfig-checker#180]
It may seen redundant to introduce such a feature at first, but here's [GNU Make](https://www.gnu.org/software/make/manual/html_node/Makefile-Contents.html)

> You cannot use comments within variable references or function calls: any instance of # will be treated literally (rather than as the start of a comment) inside a variable reference or function call.

I bet there are other instances out on the wild, that cannot do with a inline comment to disable editorconfig-checker for that specific line.

**Comment by mstruebing** [comment]
To whoever picks that up, this function needs to be adjusted: https://github.com/editorconfig-checker/editorconfig-checker/blob/main/pkg/validation/validation.go#L32

**Comment by ccoVeille** [comment]
I'm interested by the feature, so I might try to work on this when I will have free time

Please confirm the need is still there and it's OK for me to work on it

**Comment by theoludwig** [comment]
Feel free to work on it. :smile:

**Comment by ccoVeille** [comment]
OK, I will then.

**Comment by ccoVeille** [comment]
I opened

- #363
