### ISSUE TITLE
Support for darwin-arm64

### ISSUE THREAD

**Issue by noopdles** [editorconfig-checker/editorconfig-checker#187]
It would be nice to have support for darwin-amd64 in forthcoming releases - so the tool can run on newer macOS versions on Apple M1 silicon.

I have built 2.3.5, using go 1.17 (1.13 does not support darwin-arm64) and everything seems to work fine.

Please kindly consider adding support for that OS/architecture combination.

**Comment by mstruebing** [comment]
Thank for your issue. This should definitely be supported.
I hope I find time soon to work on this.

**Comment by noopdles** [comment]
See if https://github.com/editorconfig-checker/editorconfig-checker/pull/188 can be helpful. There is a bit of a caveat though which is that darwin-386 support has been gone from go since 1.15

**Comment by mstruebing** [comment]
Thank you very much.
I'm not sure about if we even need darwin-386 support, I think I was simply adding everything I was able to compile from my local machine to the Makefile so I think we can simply drop it.

**Comment by mstruebing** [comment]
Can compile the target :)
I will - hopefully - prepare a new release later today.

Feel free to ping me again if I forget about it.

**Comment by mstruebing** [comment]
🎉 
https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/2.4.0
