### ISSUE TITLE
`2.4.0` Container Image on Docker Hub

### ISSUE THREAD

**Issue by georglauterbach** [editorconfig-checker/editorconfig-checker#189]
As version `2.4.0` was releases, I expected to find a new image on DockerHub. But there is no new image. What's the rationale here? :)

**Comment by mstruebing** [comment]
Seems like dockerhub disabled automated builds without a paid plan.
I will push an updated image during the day.
Thank you for letting me know :)

**Comment by georglauterbach** [comment]
@mstruebing could you update the image on Dockerhub again?:) (CI doing this is probably a good idea for the future :D)
