### ISSUE TITLE
Improve binary file check

### ISSUE THREAD

**Issue by rasa** [editorconfig-checker/editorconfig-checker#205]
Currently, we determine if a file is binary or not by [sniffing](https://github.com/editorconfig-checker/editorconfig-checker/blob/7d6a1d2ed4077afa7db777d4ef50dc1f2b9c620d/pkg/files/files.go#L143) the content type using the first 512 characters and [seeing](https://github.com/editorconfig-checker/editorconfig-checker/blob/a277484f00a0f5de082a1a39cded3bea95e29b92/pkg/config/config_test.go#L107) if it's `text/` or `application/octet-stream`. This produces lots of false positives, such as files that are UTF16.

I think a better solution would be to determine the [charset](https://pkg.go.dev/golang.org/x/net/html/charset) and then check for binary characters. I found that the tool [dos2unix](https://linux.die.net/man/1/dos2unix), [uses](https://sourceforge.net/p/dos2unix/dos2unix/ci/master/tree/dos2unix/common.c#l2034) the characters `\x00-\x08,\x0b,\x0e-\x1f` to determine if a file is binary. This is a very widely used tool, and this check seems reasonable. Thoughts?

**Comment by mstruebing** [comment]
Sounds good, I know that this part of this application is actually a weak point so improving it in any way would be great.

**Comment by rasa** [comment]
OK, I will see if I can craft a PR that addresses this. Kinda a pain point for us. Thanks for being open to this.

**Comment by mstruebing** [comment]
Thank you very much, a PR would be really great as I do not be able to spend so much time on this tool anymore as it sometimes deserves 👍
