### ISSUE TITLE
Update docker image to 2.6.0

### ISSUE THREAD

**Issue by rasa** [editorconfig-checker/editorconfig-checker#219]
https://hub.docker.com/r/mstruebing/editorconfig-checker/tags shows the latest tag is 2.4.0. Additionally, it lists 2.3.5 on
https://hub.docker.com/r/mstruebing/editorconfig-checker#Quickstart
How can I use version 2.6.0? Can I submit a PR to help implement this bump?

**Comment by mstruebing** [comment]
The best thing would be to automate this with a GitHub-Action.
I'm not sure how much time I'm able to allocate this in the near future.

If you could provide a boilerplate GH-Action that would be great.

**Comment by rasa** [comment]
> If you could provide a boilerplate GH-Action that would be great.

@mstruebing Added in #221. Worked fine for [me](https://github.com/rasa/editorconfig-checker/actions/runs/2996700175).

**Comment by rasa** [comment]
@mstruebing ping

**Comment by bdovaz** [comment]
@mstruebing ping!
