### ISSUE TITLE
editorconfig-checker linting *.vue files?

### ISSUE THREAD

**Issue by jokay** [editorconfig-checker/editorconfig-checker#248]
I would expect **editorconfig-check** not to lint `*.vue` files but we got this:

```sh
❌ Linted [EDITORCONFIG] files with [editorconfig-checker]: Found 1 error(s) - (0.67s) (expand for details)
- Using [editorconfig-checker v2.4.0] https://megalinter.io/6.18.0/descriptors/editorconfig_editorconfig_checker
- MegaLinter key: [EDITORCONFIG_EDITORCONFIG_CHECKER]
- Rules config: identified by [editorconfig-checker]
- Number of files analyzed: [292]
--Error detail:
builds/demo/website/src/src/components/molecule/DevicesContent.vue:
	42: Wrong amount of left-padding spaces(want multiple of 2)
	43: Wrong amount of left-padding spaces(want multiple of 2)
2 errors found
```

and if we make this linter happy, we get an error for **ESLint** (vue/html-indent)

![image](https://user-images.githubusercontent.com/18613935/213981900-3af7be60-8907-435c-8011-d2dc2dcc0fd1.png)

Beside it shouldn't lint `*.vue` files, I think we should follow the advice of **ESLint** (vue/html-indent) for this :wink:

**Comment by mstruebing** [comment]
You can ignore `.vue` files, i.e. `--exclude '*.vue$'`.
I do not think we should implement ESLint rules into editorconfig-checker, these are totally different responsibilities.

**Comment by jokay** [comment]
Yes, but strange it lints `*.vue` files at all. This may have to do what MegaLinter uses as default params then.

**Comment by jokay** [comment]
This is why I asked the same question on their repo -> https://github.com/oxsecurity/megalinter/discussions/2287

**Comment by mstruebing** [comment]
Why shouldn't it?
Isn't `*.vue` just a normal text file format?

**Comment by jokay** [comment]
Well yes and no, but you are right, as text it can be linted :wink:

**Comment by OmelyanenkoV** [comment]
> --exclude '*.vue$'

How can I create a list of files that should be included in --exclude?
![image](https://user-images.githubusercontent.com/47278133/221365167-ab80a1f6-8361-46e2-b2cb-4799337bb0d5.png)
