### ISSUE TITLE
Update latest docker tag to 2.7.0

### ISSUE THREAD

**Issue by rasa** [editorconfig-checker/editorconfig-checker#250]
`latest` currently points to 2.4, but version 2.7 was released three weeks ago or so. See https://hub.docker.com/r/mstruebing/editorconfig-checker/tags .
See also https://github.com/oxsecurity/megalinter/issues/1282

**Comment by mstruebing** [comment]
Thank you, the latest tag is updated and I added a workflow step which should do this automatically.

**Comment by mstruebing** [comment]
f

**Comment by rasa** [comment]
@mstruebing Not a concern for me, but only the amd64 build is [there](https://hub.docker.com/r/mstruebing/editorconfig-checker/tags). The arm64 build is listed for 2.4.0 but not for 2.7.0 or latest.
