### ISSUE TITLE
Wrong amount of left-padding spaces in shellscript

### ISSUE THREAD

**Issue by adoyle-h** [editorconfig-checker/editorconfig-checker#253]
I'm writing a command usage with shellscript. There are some problems of text alignment.

## When `indent_style = space` and `indent_size = 2`

When using `cat <<EOF` for multi lines text, the editorconfig-checker show errors for  left-padding spaces.

But it's the content of usage, not indent of code.
I expect that the padding rule should not apply on this lines between `EOF`.

<img width="1028" alt="CleanShot 2023-02-07 at 15 47 53@2x" src="https://user-images.githubusercontent.com/1998490/217183458-1cbc4443-92d7-4386-aac6-203c628da80e.png">

## When `indent_style = tab`,

<img width="926" alt="CleanShot 2023-02-07 at 15 50 04@2x" src="https://user-images.githubusercontent.com/1998490/217183892-b410babf-abc7-4942-b518-0bda014d3e45.png">

I expect to use spaces instead of tabs to print text for usage.

**Comment by rasa** [comment]
editorconfig is not language aware. So use:
```bash
Usage() {
  # editorconfig-checker-disable
  cat <EOF
Left aligned with no
leading spaces
EOF # must not have leading spaces
  # editorconfig-checker-enable
}
```
or if you want:
```bash
Usage() {
  # editorconfig-checker-disable
  cat <-EOF
    All leading spaces 
    will be stripped off
EOF # must not have leading spaces
  # editorconfig-checker-enable
}
```

**Comment by adoyle-h** [comment]
OK. Thanks.
