### ISSUE TITLE
extract the logger into own library

### ISSUE THREAD

**Issue by mstruebing** [editorconfig-checker/editorconfig-checker#26]
The logger is a perfect, single purpose library which can be extracted into a library.

**Comment by greut** [comment]
Or simply pick any existing logging library.

**Comment by greut** [comment]
also sending everything to stderr doesn't make any grep usage friendly. Cheers,

**Comment by mstruebing** [comment]
closed, this doesn't make sense as it is to specific. I also send most things to stdout now.
Thanks for your suggestion :)
