### ISSUE TITLE
Files with unstaged changes in Git are checked twice

### ISSUE THREAD

**Issue by generalmimon** [editorconfig-checker/editorconfig-checker#270]
Consider the following state of a Git repository:

```console
$ git st
On branch master
Your branch is ahead of 'origin/master' by 7 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   src/ast.rs
        modified:   src/ast/utils.rs

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/ast/utils.rs
        modified:   src/translator.rs
```

As you can see:

* `src/ast.rs` has only staged changes,
* `src/translator.rs` has only **unstaged** changes,
* `src/ast/utils.rs` has both staged and **unstaged** changes.

The problem is that both files that have **unstaged** changes are checked twice by editorconfig-checker (which is not super critical, but weird and a bit confusing):

```console
$ ec-windows-amd64 -dry-run
.editorconfig
.gitignore
Cargo.toml
LICENSE
README.md
src/ast.rs
src/ast/utils.rs
src/ast/utils.rs
src/lib.rs
src/translator.rs
src/translator.rs
```

The problem is in this `git` invocation that editorconfig-checker uses to get the list of files to check:

https://github.com/editorconfig-checker/editorconfig-checker/blob/e946883062bacee258c9cc1eb39ca4244ae4647a/pkg/files/files.go#L98

If I run it myself, `git` prints the same list (with the same duplicates) as `ec-windows-amd64 -dry-run`. Apparently, this is expected behavior of Git for the given flags - let's use the [`-t` option](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt--t) to add status tags to filenames so we can see what's going on:

```console
$ git ls-files -t --cached --others --modified --exclude-standard
H .editorconfig
H .gitignore
H Cargo.toml
H LICENSE
H README.md
H src/ast.rs
H src/ast/utils.rs
C src/ast/utils.rs
H src/lib.rs
H src/translator.rs
C src/translator.rs
```

According to the documentation of the [`-t` option](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt--t):

> <dl>
> <dt>H</dt>
> <dd>tracked file that is not either unmerged or skip-worktree</dd>
> </dl>

> <dl>
> <dt>C</dt>
> <dd>tracked file with unstaged modification/change</dd>
> </dl>

The fix should be simple - as I understand, [`--modified`](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt---modified) ("files with an unstaged modification") is a subset of [`--cached`](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt---cached) ("all files cached in Git’s index, i.e. all tracked files"). Therefore, `--modified` cannot actually add any files which haven't been already printed by `--cached` - it can only produce duplicates (as in the described case). I think it can be safely removed, which fixes the problem with duplicates that I describe:

```diff
-$ git ls-files -t --cached --others --modified --exclude-standard
+$ git ls-files -t --cached --others --exclude-standard
 H .editorconfig
 H .gitignore
 H Cargo.toml
@@ -6,7 +6,5 @@ H LICENSE
 H README.md
 H src/ast.rs
 H src/ast/utils.rs
-C src/ast/utils.rs
 H src/lib.rs
 H src/translator.rs
-C src/translator.rs
```

**Comment by generalmimon** [comment]
So the change I suggest is to edit this line:

https://github.com/editorconfig-checker/editorconfig-checker/blob/e946883062bacee258c9cc1eb39ca4244ae4647a/pkg/files/files.go#L98

like this:

```diff
-        byteArray, err := exec.Command("git", "ls-files", "--cached", "--others", "--modified", "--exclude-standard").Output()
+        byteArray, err := exec.Command("git", "ls-files", "--cached", "--others", "--exclude-standard").Output()
```

**Comment by mstruebing** [comment]
Hey thank you, that's a pretty good and well-detailed issue!
Would you be willing to provide a PR?
