### ISSUE TITLE
Improved compatibility with Windows by providing zip binary archives

### ISSUE THREAD

**Issue by Okeanos** [editorconfig-checker/editorconfig-checker#321]
As very briefly mentioned in #204

> Then, I think it's better to have Windows releases in zip format, since there is no .tar.gz support natively, I use 7zip for that.

It would be very, very cool if you could provide Windows binary releases as `.zip` archive instead of `.tar.gz` – Windows isn't natively able to unpack/work with `.tar.gz`. This makes it especially troublesome because tools such as `winget` are also [not](https://github.com/microsoft/winget-cli/issues/2899) able to deal with `.tar.gz` either.

Providing `.zip` files would open up a lot of additional fancy integration possibilities via e.g. `winget` and related tooling making adoption on Windows way easier and nicer.

**Comment by Okeanos** [comment]
Closed by accident when going through my list of open issues. Apologies for any confusion.

**Comment by Okeanos** [comment]
@mstruebing I may be able to provide a PR for this but just to be sure I am not overlooking anything too obvious … the relevant change would be in the [Makefile](https://github.com/editorconfig-checker/editorconfig-checker/blob/main/Makefile#L155-L159) and probably involve a Windows vs. everything else check, right?

**Comment by mstruebing** [comment]
@Okeanos yes you are right. Except you would want to compress all binaries as zips.
The wrapper (php, javascript, pyhton) will need to adjust anyway so I would think one format which can be used anywhere would be better than making exceptions - if that's possible. But I guess zip is common on every OS.

**Comment by theoludwig** [comment]
This issue should probably be closed as https://github.com/editorconfig-checker/editorconfig-checker/issues/362 have been merged?
