### ISSUE TITLE
The binary may be not found after a new version release

### ISSUE THREAD

**Issue by LitoMore** [editorconfig-checker/editorconfig-checker#333]
See https://github.com/simple-icons/simple-icons/actions/runs/8553429055/job/23436630597?pr=10769.

I notice you just release a new version one hour ago. It seems there are some latency on the binary resource.

**Comment by LitoMore** [comment]
Yes, it's available now.

I see. Then it shouldn't be a long-term problem. It would be good if it had an automation script (GitHub Actions) to create a release with assets.

**Comment by mstruebing** [comment]
I agree, there is an open issue: https://github.com/editorconfig-checker/editorconfig-checker/issues/204
