### ISSUE TITLE
Install issue between version `2.7.0` and `v2.7.3`

### ISSUE THREAD

**Issue by viceice** [editorconfig-checker/editorconfig-checker#335]
We're trying to automatically upgrade this package[^1]

so we used `go install github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@2.7.0` before which works.
since `v2.7.3` we need to switch to `go install github.com/editorconfig-checker/editorconfig-checker/v2/cmd/editorconfig-checker@v2.7.3`.

What's the reason to add the `v2` after the name? it seems to be a breaking change for the v2 module.

[^1]: https://codeberg.org/forgejo/forgejo/pulls/3178

**Comment by viceice** [comment]
- #307

That seems to be the breaking change 😕

**Comment by viceice** [comment]
and the upgrade from `v2.7.3` to `2.8.0` will be broken again, because the change wasn't released there 😕

**Comment by viceice** [comment]
I think the best would be to delete `v2.7.3` or unlist it here https://pkg.go.dev/github.com/editorconfig-checker/editorconfig-checker/v2

**Comment by viceice** [comment]
another issue is that v3 isn't available on pkg.go.dev

**Comment by mstruebing** [comment]
Hey @viceice how does a package get published on pkg.go.dev? I think I've never submitted it there.

**Comment by viceice** [comment]
i think they get automatically grabbed when properly defined. your v3 releases can't be installed via `go install` because the module version suffix is still `v2` you should release a new v3 with that changed to `v3`

https://github.com/editorconfig-checker/editorconfig-checker/blob/2d43756dd83b5d9614dc4f4696ecbd52468c8c40/go.mod#L1

this version always need to correspond with your major version github tags / releases

**Comment by viceice** [comment]
also your version 2.8.0 isn't visible because of the missing `v` on the git tag

**Comment by viceice** [comment]
so you should publish a new `v2.8.1` from the 2.8.0 or just add the `v2.8.0` tag to the same commit and update the github release.

**Comment by silverwind** [comment]
> I think the best would be to delete `v2.7.3` or unlist it here https://pkg.go.dev/github.com/editorconfig-checker/editorconfig-checker/v2

go package versions can not really be deleted because go proxies already have them in cache and that cache is immutable. Just publish a fixed patch release instead.

**Comment by greut** [comment]
> It's a common misconception, but go package versions can not really be deleted because go proxies already have them in cache and that cache is immutable. Just publish a fixed patch release instead.

Indeed, but they can be retracted: https://go.dev/doc/modules/gomod-ref#retract

**Comment by klaernie** [comment]
I think this issue can be closed now, since #338 is merged.
