### ISSUE TITLE
Unable to `go run` v3 because module version does not tag version

### ISSUE THREAD

**Issue by silverwind** [editorconfig-checker/editorconfig-checker#338]
The go module version of the v3 tags is still v2, making it impossible to use v3 via `go run` and likely also `go install`:

```bash
$ go run github.com/editorconfig-checker/editorconfig-checker/v2/cmd/editorconfig-checker@v3 -help
go: github.com/editorconfig-checker/editorconfig-checker/v2/cmd/editorconfig-checker@v3.0.1: github.com/editorconfig-checker/editorconfig-checker/v2@v3.0.1: invalid version: module path includes a major version suffix, so major version must match
```

BTW I totally blame this on golang which makes v2+ modules [so hard](https://github.com/golang/go/issues/31543).

**Comment by greut** [comment]
sounds similar to:  https://github.com/editorconfig-checker/editorconfig-checker/issues/335#issuecomment-2051315338

**Comment by silverwind** [comment]
Yes, essentially the module version in go.mod and likely all go files needs to be bumped. The tagged major version must always match with the module version of the module to run.
