### ISSUE TITLE
it would be nice if editorconfig-checker could collect instances of the same issues found in adjacent lines into a single report line

### ISSUE THREAD

**Issue by klaernie** [editorconfig-checker/editorconfig-checker#359]
I've just put a bunch of generated json documents into one of our repositories, but forgot to either ignore them or adjust their indentation to fit our editorconfig.

However this lead to me getting flooded with about 10k lines of reports that the indentation was incorrect.

I think a better output format would collect consecutive issues by not outputting each line by line, but rather turning consecutive lines having the same issue into a range. Although I can imagine that this naive approach would fail in cases where each line has two errors reported (they would ping-pong, interrupting each other's consecutiveness).

**Comment by klaernie** [comment]
I'm definitely giving it a shot - looks doable for a novice like me. Expect a PR hopefully this afternoon.

**Comment by mstruebing** [comment]
If you need help or any pointers feel free to ask in here or in an (incomplete) PR! 🚀

**Comment by klaernie** [comment]
I'll definitely need help for writing the test case and somebody telling me how idiomatic the code is. But the core logic is working to 90% already.
