### ISSUE TITLE
Provide code quality report as JSON according to Code Climate specificiation

### ISSUE THREAD

**Issue by tploss** [editorconfig-checker/editorconfig-checker#365]
For projects hosted on GitLab the following feature would probably help many developers to better integrate editorconfig-checker in their GitLab CI flow.

Coming from GitLab and reading [its documentation on integrating a custom tool for code quality](https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool), we should be able to provide a code quality report as JSON according to [Code Climate specificiation](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types).

As documented in the first link, the Code Quality report artifact JSON file must contain an array of objects with the following properties:

Name | Description
-- | --
description | A description of the code quality violation.
fingerprint | A unique fingerprint to identify the code quality violation. For example, an MD5 hash.
severity | A severity string (can be info, minor, major, critical, or blocker).
location.path | The relative path to the file containing the code quality violation.
location.lines.begin | The line on which the code quality violation occurred.

This would be an alternative to the already existing gcc and default format.
As requested in #245 I'd be willing to implement this myself and open a PR.

**Comment by klaernie** [comment]
interesting, that #367 did not close this issue.

**Comment by ccoVeille** [comment]
> interesting, that merging #367 did not close this issue.

The PR was mentioning "more details #id",
not "Fix #id", or "Closes #id"

It seems "normal"
