### ISSUE TITLE
List supported EditorConfig features

### ISSUE THREAD

**Issue by sanmai-NL** [editorconfig-checker/editorconfig-checker#37]
E.g., it currently cannot be determined from the documentation whether `editorconfig-checker` supports validating text encodings.

**Comment by mstruebing** [comment]
Thank you, good point.

Currently, text-encoding isn't validated.
Maybe you can propose a change in a pull request?

**Comment by sanmai-NL** [comment]
Could you please elaborate what change? Non-maintainers don't know what features `editorconfig-checker` implements, so documenting that is not suitable for them.

**Comment by mstruebing** [comment]
Ah okay sorry, I've thought everyone would be able to go through the code. I will try to push an update to the readme soon.
