### ISSUE TITLE
(Default) excludes and regex behavior

### ISSUE THREAD

**Issue by Okeanos** [editorconfig-checker/editorconfig-checker#370]
I recently went through the file based excludes again for a project and when reading through the [default excludes](https://github.com/editorconfig-checker/editorconfig-checker?tab=readme-ov-file#default-excludes) I may have (originally) misunderstood some things.

The regex matching behavior isn't explicitly described and an exclusion such as `^composer\\.lock$` appears to tell editorconfig-checker to ignore a file that is named _exactly_ `composer.lock`. The exclusion `\\.jpg$` is supposed to match all files having a `.jpg` extension and `min\\.js$` matches anything ending in `min.js`, right?

Based on that understanding I want to ignore files called `.terraform.lock.hcl` and initially used the exclude pattern `^\\.terraform\\.lock\\.hcl` for that.

To my surprise the following happened:

```output
$ cat .ecrc
{
    "exclude": [
        "^\\.terraform\\.lock\\.hcl$"
    ]
}
$ editorconfig-checker
modules/repositories/.terraform.lock.hcl:
	5: Wrong indentation type(spaces instead of tabs)
```

When I now switch the regex to 

```output
$ cat .ecrc
{
    "exclude": [
        "\\.terraform\\.lock\\.hcl$"
    ]
}
```

editorconfig-checker successfully runs without finding any validation errors. What am I doing wrong? From what I can tell the `^...$` regex has a "problem" where it only matches files in the scanned root directory, not any subfolders. A look at the [`IsExcluded`](https://github.com/editorconfig-checker/editorconfig-checker/blob/main/pkg/files/files.go#L35-L51) function appears to confirm that where the regex test is used with a relative path inside the scanned root directory and not the filename.

Am I understanding all of this correctly and if so, would it make sense to:

- describe that behavior in the docs (with some examples) in detail?
- change some of the default excludes (starting with `^`) to also apply in subfolders out of the box (I am thinking about multi-module/monorepo structures)?

**Comment by klaernie** [comment]
Your observations are totally correct - you copied the `composer.lock` exclusion rule, not being aware that the regex is applied to paths and not filenames. This of cause is confusing. I hope my rewording in #372 makes this much more easy to grasp.
