### ISSUE TITLE
enforce the conventional commits format via the CI

### ISSUE THREAD

**Issue by ccoVeille** [editorconfig-checker/editorconfig-checker#379]
We added a comment about the need for contributors to respect the conventional commits format

Checking the commit message format is boring task to do manually

_Originally posted by @ccoVeille in https://github.com/editorconfig-checker/editorconfig-checker/pull/378#discussion_r1758592131_

**Comment by echoix** [comment]
For this, take a look at https://github.com/conventional-changelog/commitlint, or anything in https://www.conventionalcommits.org/en/about/

If you only use squash-merge, it might be better to leave it up to the maintainer that merges the PR to make the commit title respect the convention at the time of squash-merging

**Comment by theoludwig** [comment]
Well, it's already enforced: https://github.com/editorconfig-checker/editorconfig-checker/blob/f7b7cb7326cb657e87bc3093da4811c97892659e/.github/workflows/ci.yml#L16

**Comment by klaernie** [comment]
> If you only use squash-merge, it might be better to leave it up to the maintainer that merges the PR to make the commit title respect the convention at the time of squash-merging

Enforcing conventional commits makes doubly sense here - the maintainer merging must know if the merge is a breaking change or what the most relevant subject is to write the commit message of the merge. Maybe this should be automated, so the PR title always reflects the breaking change flag.
