### ISSUE TITLE
Deprecate by a warning the `.ecrc` configuration file

### ISSUE THREAD

**Issue by theoludwig** [editorconfig-checker/editorconfig-checker#388]
In #375, a new configuration file has been added: `.editorconfig-checker.json`.

In v4.0.0, we plan to drop the naming `ec` to use `editorconfig-checker` (#371), so we thought that we should deprecate usage of `.ecrc`, so that we can remove it in v4.0.0.

However, currently it is only deprecated in the `README.md`, we should **deprecate it at runtime**, by emitting a warning so that it will be easier for users to upgrade.

Similarly, it has been suggested to emit warnings in #386.

**Comment by abuzaforfagun** [comment]
Hi,
I am interested in fixing it.
