### ISSUE TITLE
Color output broken on Windows

### ISSUE THREAD

**Issue by sylveon** [editorconfig-checker/editorconfig-checker#74]
![image](https://user-images.githubusercontent.com/6440374/62560619-6f3f7b00-b84b-11e9-9844-b6d5a697d693.png)

**Comment by mstruebing** [comment]
Hey, thank you for your issue.
As far as I can see in my quick google-fu, Windows 10 should be capable to support ANSI-colors.
Which Windows version are you using?

If you are using a Windows version < 10 I could try to remove the colour output fully because it is not supported for Windows < 10.

**Comment by mstruebing** [comment]
Are you able to build go code? If so it would be *super* helpful if you could try out #75

**Comment by sylveon** [comment]
I'm on the latest Windows 10 update, which means that technically I should see color output: https://devblogs.microsoft.com/commandline/24-bit-color-in-the-windows-console/ and I do see it when I run [this batch file](https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011) which uses ANSI color codes.

To make things weirder, if I try on the new Terminal app, I even get correctly colored output for editorconfig-checker.

See this screenshot:
![image](https://user-images.githubusercontent.com/6440374/62645113-93698d80-b919-11e9-8727-dbb3349b8e62.png)

**Comment by mstruebing** [comment]
I honestly doesn't have any clue what could be the cause of it. I'm using ANSI-colors too, is there any difference between them?

Do you have any idea how this could be fixed?

**Comment by sylveon** [comment]
It seems that it needs to be explicitly enabled, according to documentation
https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences (by doing [this](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#example-of-sgr-terminal-sequences))

Windows 10 builds higher than 10586 all support this flag and it should make color output work.

Builds older than that still won't be able to output color, so determining at runtime might be ideal. Of course, it's possible to use the native Windows API for coloring instead of using that flag meaning that even XP would display the text with correct colors. I think that there's some go packages that provide cross-platform coloring support using that API on Windows.

**Comment by mstruebing** [comment]
Hey, with new version (current master) I've introduced a flag which disables the color output with the flag `-no-color`.

Do you think this is sufficient to close this issue? While time passes, every windows terminal should support color I think.

**Comment by sylveon** [comment]
Should be good enough
