### ISSUE TITLE
Option to only disable indent_size check

### ISSUE THREAD

**Issue by ivy-cst** [editorconfig-checker/editorconfig-checker#94]
It would be great to be able to just disable `indent_size` check but not `indent_style` check.

Currently it is only possible to `-disable-indentation` which means disabling `indent_size` and `indent_style` check.

Unfortunately there are many use cases where `indent_size` is not correct in complex files because every language handles some special cases differently. Also if you have _blank lines_  with just the correct number of spaces the check fails at the moment with "Wrong amount of left-padding spaces(want multiple of x)"

At the moment it is not possible in our workspace to fix all `indent_size` problems, but we would like to check the `indent_style` only but not the `indent_size`.

**Comment by mstruebing** [comment]
Thanks for reporting this issue.

I can feel your pain with this and agree to implement that.
If you want, you could create a pull request for that, that would be really nice.

**Comment by ivy-cst** [comment]
Thank you so much, it works perfectly!
