### ISSUE TITLE
Read excludes from `.gitignore` instead of using the git added files

### ISSUE THREAD

**Issue by mstruebing** [editorconfig-checker/editorconfig-checker#99]
Currently we use `git ls-tree -r --name-only HEAD` to find files which should be checked.
It seems it would be better to read the `.gitignore` file, see: https://github.com/editorconfig-checker/editorconfig-checker.javascript/issues/111#issuecomment-567628706

**Comment by mightyiam** [comment]
Thank you for considering this, @mstruebing.

Trying to imitate what git does in a project would probably be a bit more complicated than a single top-level `.gitignore`. If I remember correctly, any directory can have a `.gitignore` file and it gets rather complicated to re-implement all that.

Perhaps one of these could help, if it at all makes sense to execute git for this purpose.
https://git-scm.com/docs/git-check-ignore
https://git-scm.com/docs/git-ls-files

**Comment by mstruebing** [comment]
fixed by #135
